name: Node.js CI

on:
  pull_request:
    branches:
      - lesson/34-functional-programming

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      working-directory: ./lessons/34-functional-programming
      run: npm ci
    - name: Run tests
      working-directory: ./lessons/34-functional-programming
      run: npm test
